FROM node:12.14-alpine

WORKDIR /usr/src

# Set API url
ARG API_URL
ENV API_URL $API_URL

ARG API_URL_BROWSER
ENV API_URL_BROWSER $API_URL_BROWSER

# Set host
ENV HOST 0.0.0.0

# Set and expose port
ENV PORT 3000
EXPOSE $PORT

# Install dependences
COPY package*.json ./

# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#node-gyp-alpine
RUN apk add --no-cache --virtual .gyp python make g++ \
    && npm ci \
    && apk del .gyp

CMD ["npm", "run", "dev"]
